# Source of truth for French translations. Regenerates Localizable.xcstrings.
# Usage: python3 scripts/strings.py
import json, pathlib

NB = " "  # French non-breaking space before ? ! :
FR = {
    "Capture": "Capture",
    "Preview": "Aperçu",
    "Screenshots": "Captures d’écran",
    "Videos": "Vidéos",
    "No Device": "Aucun appareil",
    "Connect an iPhone to get started.": "Connectez un iPhone pour commencer.",
    "Connected": "Connecté",
    "No Screenshots Yet": "Aucune capture d’écran",
    "Screenshots you take will appear here.": "Vos captures d’écran apparaîtront ici.",
    "No Videos Yet": "Aucune vidéo",
    "Screen recordings you make will appear here.": "Vos enregistrements vidéo apparaîtront ici.",
    "Camera Access Required": "Accès à la caméra requis",
    "Capture needs camera access to display your iPhone's screen.": "Capture a besoin de l’accès à la caméra pour afficher l’écran de votre iPhone.",
    "Allow Access": "Autoriser l’accès",
    "Open System Settings": "Ouvrir les Réglages Système",
    "Connect your iPhone": "Connectez votre iPhone",
    "Plug your iPhone into this Mac with a USB cable to preview its screen, take screenshots and record videos.": "Branchez votre iPhone à ce Mac avec un câble USB pour prévisualiser son écran, prendre des captures et enregistrer des vidéos.",
    "Need Help?": f"Besoin d’aide{NB}?",
    "Your iPhone doesn't appear?": f"Votre iPhone n’apparaît pas{NB}?",
    "Unlock your iPhone and tap Trust when asked.": f"Déverrouillez votre iPhone et touchez «{NB}Se fier{NB}» si on vous le demande.",
    "Use a data cable: some cables can only charge.": f"Utilisez un câble de données{NB}: certains câbles ne font que charger.",
    "Try unplugging your iPhone and plugging it back in.": "Essayez de débrancher puis de rebrancher votre iPhone.",
    "Back": "Retour",
    "Continue": "Continuer",
    "Get Started": "Commencer",
    "Welcome to Capture": "Bienvenue dans Capture",
    "Take pixel-perfect screenshots and screen recordings of your iPhone, with the clean 9:41 status bar Apple uses in its own product shots.": "Réalisez des captures d’écran et des vidéos impeccables de votre iPhone, avec la barre d’état épurée à 9:41 qu’Apple utilise dans ses propres visuels.",
    "Everything QuickTime does, only faster and more powerful.": "Tout ce que fait QuickTime, en plus pratique et plus complet.",
    "Built for clean iPhone captures": "Pensé pour des captures iPhone impeccables",
    "Capture your iPhone screen in one click, at full native resolution.": "Capturez l’écran de votre iPhone en un clic, en pleine résolution.",
    "Screen Recordings": "Capture vidéo",
    "Record videos with sound, straight from your iPhone.": "Enregistrez des vidéos avec le son, directement depuis votre iPhone.",
    "A Perfect Status Bar": "Une barre d’état parfaite",
    "9:41, full battery and full signal, automatically.": "9:41, batterie pleine et réseau au maximum, automatiquement.",
    "Device Frames": "Cadres d’appareil",
    "Add an iPhone frame to your captures when you edit them.": "Ajoutez un cadre d’iPhone à vos captures lors de l’édition.",
    "Recents": "Récents",
    "Find all your captures in one place.": "Retrouvez toutes vos captures au même endroit.",
    "Allow Camera Access": "Autorisez l’accès à la caméra",
    "macOS treats your iPhone's screen like a camera. Capture needs this access to display and record it.": "macOS considère l’écran de votre iPhone comme une caméra. Capture a besoin de cet accès pour l’afficher et l’enregistrer.",
    "Your captures never leave your Mac.": "Vos captures ne quittent jamais votre Mac.",
    "Access granted": "Accès autorisé",
    "Screenshot": "Capture d’écran",
    "Record Video": "Capture vidéo",
    "Stop Recording": "Arrêter l’enregistrement",
    "Take Screenshot": "Prendre une capture d’écran",
    "Open Capture Folder": "Ouvrir le dossier Capture",
    "Couldn't Save the Capture": "Impossible d’enregistrer la capture",
    "OK": "OK",
    "Settings": "Réglages",
    "Customize your experience with Capture.": "Personnalisez votre expérience avec Capture.",
    "Storage": "Stockage",
    "Choose where your screenshots and recordings are saved.": "Choisissez l’emplacement de sauvegarde de vos captures et enregistrements.",
    "Erase Data": "Effacer les données",
    "Remove all the screenshots, recordings and exports made with Capture.": "Supprimez toutes les captures, vidéos et exports réalisés avec Capture.",
    "Erase All…": "Tout effacer…",
    "Files are moved to the Trash. Other files in the folder are left untouched.": "Les fichiers sont placés dans la corbeille. Les autres fichiers du dossier ne sont pas touchés.",
    "Move all captures to the Trash?": f"Placer toutes les captures dans la corbeille{NB}?",
    "%lld files will be moved to the Trash.": "%lld fichiers seront placés dans la corbeille.",
    "Couldn't Erase the Captures": "Impossible d’effacer les captures",
    "Default Quality": "Qualité par défaut",
    "Settings applied to your next captures.": "Paramètres appliqués à vos prochaines captures.",
    "1x (Original Size)": "1x (taille originale)",
    "½x (Half Size)": "½x (moitié)",
    "Include Sound (Video)": "Inclure le son (vidéo)",
    "Appearance": "Apparence",
    "Adapt the interface to your preferences.": "Adaptez l’interface à vos préférences.",
    "Theme": "Thème",
    "Match System": "Comme le système",
    "Light": "Clair",
    "Dark": "Sombre",
    "Advanced Options": "Options avancées",
    "Extra features for advanced users.": "Fonctionnalités supplémentaires pour les utilisateurs avancés.",
    "File Names": "Nom des fichiers",
    "Device, Date and Time": "Appareil, date et heure",
    "Date and Time": "Date et heure",
    "Numbered": "Numérotés",
    "Custom": "Personnalisé",
    "File Name": "Nom du fichier",
    "Example: %@": f"Exemple{NB}: %@",
    "Organize By": "Organiser par",
    "Device": "Appareil",
    "Date": "Date",
    "Time": "Heure",
    "Counter": "Compteur",
    "Type": "Type",
    "Video": "Vidéo",
    "Export to the Capture Folder": "Exporter dans le dossier de capture",
    "Exports are saved in the _Exports folder, without a dialog.": "Les exports sont enregistrés dans le dossier _Exports, sans fenêtre de dialogue.",
    "Export": "Exporter",
    "Exported": "Exporté",
    "Help": "Aide",
    "Need help? Read the documentation or contact us.": f"Besoin d’aide{NB}? Consultez la documentation ou contactez-nous.",
    "View Documentation": "Voir la documentation",
    "Contact Us": "Nous contacter",
    "Updates": "Mises à jour",
    "Check Automatically": "Rechercher automatiquement",
    "Last checked %@": "Dernière recherche %@",
    "Check for Updates…": "Rechercher les mises à jour…",
    "Version %@ (%@)": "Version %@ (%@)",
    "Model": "Modèle",
    "Automatic (%@)": "Automatique (%@)",
    "Same Screen as This Capture": "Même écran que cette capture",
    "Other Models": "Autres modèles",
    "This model has a different screen size: the capture is scaled to fill it.": "Ce modèle a une taille d’écran différente : la capture est agrandie pour le remplir.",
    "Frames aren't available for this capture.": "Les cadres ne sont pas disponibles pour cette capture.",
    "No Background": "Sans fond",
    "Suggested from the capture": "Suggéré d’après la capture",
    "Remove": "Supprimer",
    "Add Colors": "Ajouter des couleurs",
    "Paste one or more hex codes.": "Collez un ou plusieurs codes hexadécimaux.",
    "Or pick a color": "Ou choisissez une couleur",
    "Add Color": "Ajouter la couleur",
    "Cancel": "Annuler",
    "Add": "Ajouter",
    "Add a Gradient": "Ajouter un dégradé",
    "Start": "Début",
    "End": "Fin",
    "Space Gray": "Gris sidéral",
    "Gold": "Or",
    "White": "Blanc",
    "Yellow": "Jaune",
    "Coral": "Corail",
    "Red": "(PRODUCT)RED",
    "Green": "Vert",
    "Purple": "Mauve",
    "Midnight Green": "Vert nuit",
    "Graphite": "Graphite",
    "Pacific Blue": "Bleu Pacifique",
    "Midnight": "Minuit",
    "Starlight": "Lumière stellaire",
    "Pink": "Rose",
    "Sierra Blue": "Bleu alpin",
    "Alpine Green": "Vert alpin",
    "Space Black": "Noir sidéral",
    "Deep Purple": "Violet intense",
    "Teal": "Sarcelle",
    "Ultramarine": "Outremer",
    "Mist Blue": "Bleu brume",
    "Sage": "Sauge",
    "Lavender": "Lavande",
    "Cloud White": "Blanc nuage",
    "Light Gold": "Or clair",
    "Sky Blue": "Bleu ciel",
    "Cosmic Orange": "Orange cosmique",
    "Deep Blue": "Bleu intense",
    "Glacier": "Glacier",
    "Dynamic Island": "Dynamic Island",
    "Video Editor": "Éditeur vidéo",
    "See your iPhone screen live, then capture it.": "Visualisez l’écran de votre iPhone en direct, puis capturez-le.",
    "Frame, style and export your screenshots.": "Encadrez, mettez en forme et exportez vos captures.",
    "Layout": "Disposition",
    "Orientation": "Orientation",
    "Automatic": "Automatique",
    "Portrait": "Portrait",
    "Landscape Left": "Paysage à gauche",
    "Landscape Right": "Paysage à droite",
    "Upside Down": "À l’envers",
    "Ratio": "Ratio",
    "Auto": "Auto",
    "1:1": "1:1",
    "9:16": "9:16",
    "16:9": "16:9",
    "The device is resized to fit inside the chosen ratio.": "L’appareil est redimensionné pour tenir dans le ratio choisi.",
    "Trim, adjust and export your videos.": "Coupez, ajustez et exportez vos vidéos.",
    "Recent Videos": "Vidéos récentes",
    "Undo": "Annuler",
    "Redo": "Rétablir",
    "Play": "Lire",
    "Pause": "Pause",
    "Split at Playhead": "Couper à la tête de lecture",
    "Delete Segment": "Supprimer le segment",
    "Zoom Out": "Zoom arrière",
    "Zoom In": "Zoom avant",
    "Audio": "Audio",
    "Remove Track": "Retirer la piste",
    "Add a Track (Music, Voice-Over…)": "Ajouter une piste (musique, voix off…)",
    "Frame Rate": "Fréquence d’images",
    "Include Sound": "Inclure le son",
    "Optimize for Web Sharing": "Optimiser pour le partage web",
    "Exporting…": "Exportation…",
    "Export Video…": "Exporter la vidéo…",
    "Same as Source (%@)": "Comme la source (%@)",
    "1080p (%@)": "1080p (%@)",
    "720p (%@)": "720p (%@)",
    "Same as Source (%lld fps)": "Comme la source (%lld ips)",
    "60 fps": "60 ips",
    "30 fps": "30 ips",
    "24 fps": "24 ips",
    "Couldn't Export the Video": "Impossible d’exporter la vidéo",
    "Tools": "Outils",
    "Cut": "Couper",
    "Rotate": "Pivoter",
    "Speed": "Vitesse",
    "Volume": "Volume",
    "Reset": "Réinitialiser",
    "Sound keeps its pitch when the speed changes.": "Le son garde sa hauteur quand la vitesse change.",
    "iPhone Sound": "Son de l’iPhone",
    "Mute": "Couper le son",
    "Added Track": "Piste ajoutée",
    "MP4 (Recommended)": "MP4 (recommandé)",
    "MOV (HEVC)": "MOV (HEVC)",
    "Natural": "Naturel",
    "Desert": "Sable",
    "Burgundy": "Bordeaux",
    "Show in Finder": "Afficher dans le Finder",
    "Export Options": "Options d’exportation",
    "Recent Captures": "Captures récentes",
    "See All": "Tout voir",
    "Move to Trash": "Placer dans la corbeille",
    "Close": "Fermer",
    "Format": "Format",
    "Resolution": "Résolution",
    "Margin": "Marge",
    "Shadow": "Ombre",
    "Copy": "Copier",
    "Copied": "Copié",
    "Export…": "Exporter…",
    "Couldn't Export the Screenshot": "Impossible d’exporter la capture",
    "edited": "modifiée",
    "Device Frame": "Cadre de l’appareil",
    "Background": "Fond",
    "None": "Aucun",
    "PNG (High Quality)": "PNG (haute qualité)",
    "JPEG": "JPEG",
    "HEIC": "HEIC",
    "Black": "Noir",
    "Silver": "Argent",
    "Blue": "Bleu",
    "Color": "Couleur",
    "Gradient": "Dégradé",
    "Image": "Image",
    "Choose": "Choisir",
    "Choose where to save your screenshots and videos.": "Choisissez où enregistrer vos captures d’écran et vidéos.",
    "Choose Where to Save": "Choisissez où enregistrer",
    "Your screenshots and videos will be saved in this folder.": "Vos captures d’écran et vidéos seront enregistrées dans ce dossier.",
    "Change…": "Modifier…",
    "Capture can't access this folder. Choose another one, or allow access in System Settings > Privacy & Security > Files and Folders.": "Capture ne peut pas accéder à ce dossier. Choisissez-en un autre, ou autorisez l’accès dans Réglages Système > Confidentialité et sécurité > Fichiers et dossiers.",
    "No image has been received from the iPhone yet.": "Aucune image n’a encore été reçue de l’iPhone.",
    "The file could not be written.": "Le fichier n’a pas pu être enregistré.",
    "Access was denied. You can turn it on in System Settings > Privacy & Security > Camera.": "L’accès a été refusé. Vous pouvez l’activer dans Réglages Système > Confidentialité et sécurité > Caméra.",
}

INFO_PLIST_FR = {
    "NSCameraUsageDescription": "Capture utilise l’accès à la caméra pour afficher et enregistrer l’écran de votre iPhone connecté.",
}

def catalog(entries):
    return {
        "sourceLanguage": "en",
        "strings": {
            key: {"localizations": {"fr": {"stringUnit": {"state": "translated", "value": value}}}}
            for key, value in sorted(entries.items())
        },
        "version": "1.0",
    }

root = pathlib.Path(__file__).resolve().parent.parent / "Capture" / "Resources"
for name, entries in [("Localizable", FR), ("InfoPlist", INFO_PLIST_FR)]:
    path = root / f"{name}.xcstrings"
    path.write_text(json.dumps(catalog(entries), ensure_ascii=False, indent=2) + "\n")
    print(f"Wrote {len(entries)} strings to {path.name}")
